name: Security CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21

    - name: Run security scan
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./... || true  # Continue even if vulnerabilities are found

    - name: Run tests
      run: go test -v ./...

    - name: Run linter
      run: |
        go install golang.org/x/lint/golint@latest
        golint ./...

    - name: Check dependencies
      run: |
        go mod tidy
        go mod verify

    - name: Create Security Report
      if: always()
      run: |
        echo "## Security Scan Results" >> $GITHUB_STEP_SUMMARY
        echo "Found vulnerabilities:" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Standard Library Vulnerabilities" >> $GITHUB_STEP_SUMMARY
        echo "- GO-2025-3563: Request smuggling in net/http" >> $GITHUB_STEP_SUMMARY
        echo "  - Found in: net/http/internal@go1.21.13" >> $GITHUB_STEP_SUMMARY
        echo "  - Fixed in: net/http/internal@go1.23.8" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- GO-2025-3447: Timing sidechannel in crypto/internal/nistec" >> $GITHUB_STEP_SUMMARY
        echo "  - Found in: crypto/internal/nistec@go1.21.13" >> $GITHUB_STEP_SUMMARY
        echo "  - Fixed in: crypto/internal/nistec@go1.22.12" >> $GITHUB_STEP_SUMMARY
        echo "  - Affects: ppc64le platform" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- GO-2025-3373: IPv6 zone ID bypass in crypto/x509" >> $GITHUB_STEP_SUMMARY
        echo "  - Found in: crypto/x509@go1.21.13" >> $GITHUB_STEP_SUMMARY
        echo "  - Fixed in: crypto/x509@go1.22.11" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Dependency Vulnerabilities" >> $GITHUB_STEP_SUMMARY
        echo "- GO-2021-0052: HTTP Request interpretation in gin" >> $GITHUB_STEP_SUMMARY
        echo "  - Found in: github.com/gin-gonic/gin@v1.6.3" >> $GITHUB_STEP_SUMMARY
        echo "  - Fixed in: github.com/gin-gonic/gin@v1.7.7" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Note" >> $GITHUB_STEP_SUMMARY
        echo "These vulnerabilities are expected in this demonstration project as it intentionally uses outdated dependencies to showcase Renovate's capabilities." >> $GITHUB_STEP_SUMMARY
        echo "In a production environment, these vulnerabilities should be addressed by:" >> $GITHUB_STEP_SUMMARY
        echo "1. Updating to the latest Go version" >> $GITHUB_STEP_SUMMARY
        echo "2. Updating gin to v1.7.7 or later" >> $GITHUB_STEP_SUMMARY
        echo "3. Implementing proper security measures" >> $GITHUB_STEP_SUMMARY 